// Code generated by protoc-gen-go.
// source: token.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	token.proto

It has these top-level messages:
	RawInfo
	Token
*/
package auth

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RawInfo struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Deviceid         *string `protobuf:"bytes,2,opt,name=deviceid" json:"deviceid,omitempty"`
	ExpiredTime      *int64  `protobuf:"varint,3,opt,name=expired_time" json:"expired_time,omitempty"`
	Option           []byte  `protobuf:"bytes,4,opt,name=option" json:"option,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RawInfo) Reset()         { *m = RawInfo{} }
func (m *RawInfo) String() string { return proto.CompactTextString(m) }
func (*RawInfo) ProtoMessage()    {}

func (m *RawInfo) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *RawInfo) GetDeviceid() string {
	if m != nil && m.Deviceid != nil {
		return *m.Deviceid
	}
	return ""
}

func (m *RawInfo) GetExpiredTime() int64 {
	if m != nil && m.ExpiredTime != nil {
		return *m.ExpiredTime
	}
	return 0
}

func (m *RawInfo) GetOption() []byte {
	if m != nil {
		return m.Option
	}
	return nil
}

type Token struct {
	Raw              *RawInfo `protobuf:"bytes,1,opt,name=raw" json:"raw,omitempty"`
	Cipher           []byte   `protobuf:"bytes,2,opt,name=cipher" json:"cipher,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}

func (m *Token) GetRaw() *RawInfo {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Token) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

func init() {
}
